@startuml
!includeurl https://raw.githubusercontent.com/omahoito/rfc/master/Styles.iuml
header
Module diagram generated with plantuml.com to github.com/omahoito/definitinotification. \
CC-BY-4.0 Sotedigi Oy 2021. \
To change the picture, make a pull request with changes to modules.plantuml and README.md.
endheader
scale 0.55

actor user

folder "Tools" as tools {
    component "oda-cms" as cms
}

folder "Omaolo (ODA2)" as oda {
    'component nginx
    component "oda-web-front" as front

    folder "Proxy" {
        component nginx
        component "oda-gateway" as gateway
    }

    component "AVPH" as AVPH
    component "File laundry" as laundry

    folder "Services" {
        component "oda-backend" as backend
        component "oda-idp" as idp
        component "oda-esb" as esb

        component "oda-fhir-service" as fhir
        component "oda-phr" as phr
        component "oda-logging-service" as logging
        component "oda-cqrs-service" as cqrs
        component "oda-covid-contact-service" as covid

        component "oda-analytics-service" as analytics
        component "oda-notification-service" as notification
        component "oda-cds-service" as cds
        component "oda-media-storage" as mediastorage
        component "oda-feedback-service" as feedback
        component "oda-conversion-service" as conversion
    }

    folder Storage {
        database "PostgreSQL" as postgres
        database "MongoDB" as mongo
        database "Redis" as redis
        database Minio
    }

    folder Libraries {
        component "oda-service-common" as servicecommon
        component "oda-fhir-service-common" as fhirservicecommon
        component "oda-context-client"
        component "oda-form-generator"
    }
}

folder "External systems" as ext {
    folder "Suomi.fi" {
        component "e-Identification" as eident
    }
    folder "Electronic Health Record" as EHRfolder {
        component EHR
        component "Minimum Context Server" as context
    }
    component "ControlHub dashboard" as dashboard
    component "Workflow management system" as workflowmanagement
    folder "Duodecim (ODA 1)" {
        component "Questionnaire\ndatabase" as VKT
        component "ODA 1 API gateway" as ODA1
        component "EBMeDS\nDecision support system" as EBMeDS
        ODA1 --> EBMeDS
    }
    folder "Kanta" {
        component "Omatietovaranto" as omatietovaranto
    }
    folder "Kela Koronavilkku" {
        component "Publish Token API" as koronavilkkuTokenApi
    }
}



analytics --> fhir
analytics --> logging

gateway --> conversion : cloud-gateway
gateway --> fhir : cloud-gateway
gateway --> cqrs : cloud-gateway
gateway --> backend
backend --> idp : token
backend --> logging : session and frontend log
gateway --> mediastorage : cloud-gateway
gateway --> notification : cloud-gateway
backend --> redis : session
gateway --> covid: cloud-gateway

covid --> phr
covid --> koronavilkkuTokenApi
covid --> logging
covid --> postgres
covid --> fhir

user --> front : browser
user --> nginx : idp

cds --> postgres
cds --> logging

dashboard --> nginx : analytics
dashboard --> nginx : feedback

esb --> EHR
esb --> logging
esb <--> AVPH
AVPH --> EHR

feedback -> phr

fhir --> ODA1
fhir --> phr
fhir --> logging
fhir --> esb
fhir --> cds
fhir --> notification
fhir --> omatietovaranto

cqrs --> phr
cqrs --> logging

front --> nginx

gateway --> redis : session

idp --> context
idp --> fhir
idp --> eident

logging --> mongo

mediastorage --> phr
mediastorage --> Minio
mediastorage <--> laundry

nginx --> analytics
nginx --> feedback
nginx --> gateway
nginx --> idp

notification --> phr
notification --> user : websocket
notification --> workflowmanagement

phr --> postgres

' Layout fixes
user -[hidden]- oda
EHR -[hidden]down- context
Storage -[hidden]right-> Libraries
servicecommon -[hidden]right-> fhirservicecommon

@enduml
