@startuml
header
Sequence diagram for blood pressure follow-up
endheader

participant ODA_WEB_UI
participant ODA_FHIR_API

box "ODA 2" #LightBlue
    participant ODA_WEB_UI
    participant ODA_FHIR_API
end box
participant ODA_PHR

ODA_WEB_UI -> ODA_FHIR_API: POST [oda-fhir-base]/CarePlan/[id]/$refresh-status
ODA_FHIR_API -> ODA_PHR: GET [oda-phr-base]/Observation?code=http://loinc.org|85354-9&patient=1&date>=2018-01-01&date<=2018-01-21
ODA_FHIR_API <- ODA_PHR: HTTP 200 OK [Bundle of Observations for whole follow-up]
group Case: (Four days with 2 Observations) OR (time period exceeded) 
ODA_FHIR_API <- ODA_FHIR_API: CarePlan.activity.detail.status = completed
end
group Case: CarePlan.activity.detail.status = not-started AND number of Observations > 0
ODA_FHIR_API <- ODA_FHIR_API: CarePlan.activity.detail.status = in-progress
end
ODA_FHIR_API -> ODA_PHR: PUT [oda-phr-base]/CarePlan/[id]/
ODA_FHIR_API <- ODA_PHR: HTTP 200 OK


ODA_WEB_UI <-- ODA_FHIR_API: HTTP 200 OK [Bundle with CarePlan and blood pressure Observations of current day]

group Case: (Follow-up not complete) AND (number of current day observations < 2) 
ODA_WEB_UI -> ODA_FHIR_API: POST [oda-phr-base]/Observation/
ODA_WEB_UI <-- ODA_FHIR_API: HTTP 201 CREATED

end

@enduml
